ALTER TABLE "UserIdentity"
  ADD COLUMN "lastAuthenticatedAt" TIMESTAMPTZ,
  ADD COLUMN "passwordChangedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "TenantMembership"
  ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "RefreshSession"
  ADD COLUMN "clientContext" JSONB,
  ADD COLUMN "reusedAt" TIMESTAMPTZ,
  ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX "RefreshSession_familyHash_idx" ON "RefreshSession"("familyHash");

ALTER TABLE "ServiceIdentity"
  ADD COLUMN "issuer" TEXT NOT NULL DEFAULT 'migration-required',
  ADD COLUMN "credentialHash" TEXT NOT NULL DEFAULT 'migration-required',
  ADD COLUMN "revokedAt" TIMESTAMPTZ,
  ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ServiceIdentity"
  ALTER COLUMN "issuer" DROP DEFAULT,
  ALTER COLUMN "credentialHash" DROP DEFAULT;

ALTER TABLE "SupportGrant"
  ADD COLUMN "auditRefs" JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "SupportGrant" ALTER COLUMN "auditRefs" DROP DEFAULT;

CREATE INDEX "SupportGrant_tenantId_supportActorId_idx"
  ON "SupportGrant"("tenantId", "supportActorId");
